#WAP to input eight number from user and display all the unique number once 
s = set()
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 2: ")
s.add(int(n))
n = input("enter number 3: ")
s.add(int(n))
n = input("enter number 4: ")
s.add(int(n))
n = input("enter number 5: ")
s.add(int(n))
n = input("enter number 6: ")
s.add(int(n))
n = input("enter number 7: ")
s.add(int(n))
n = input("enter number 8: ")
s.add(int(n))
print(n)
